/* Generated by Yosys 0.7 (git sha1 61f6811, i686-w64-mingw32.static-gcc 4.9.3 -Os) */

module Q8Moore(clk, rst, j, w);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  input clk;
  input j;
  reg [4:0] ps;
  input rst;
  output w;
  NOT _30_ (
    .A(_21_),
    .Y(_12_)
  );
  NOT _31_ (
    .A(_25_),
    .Y(_14_)
  );
  NAND _32_ (
    .A(_14_),
    .B(_12_),
    .Y(_16_)
  );
  NOR _33_ (
    .A(_16_),
    .B(_09_),
    .Y(_17_)
  );
  NOR _34_ (
    .A(_17_),
    .B(_26_),
    .Y(_27_)
  );
  NOT _35_ (
    .A(_26_),
    .Y(_18_)
  );
  NOT _36_ (
    .A(_28_),
    .Y(_19_)
  );
  NOT _37_ (
    .A(_29_),
    .Y(_20_)
  );
  NAND _38_ (
    .A(_20_),
    .B(_19_),
    .Y(_22_)
  );
  NOR _39_ (
    .A(_22_),
    .B(_09_),
    .Y(_23_)
  );
  NOR _40_ (
    .A(_23_),
    .B(_18_),
    .Y(_10_)
  );
  NOR _41_ (
    .A(_18_),
    .B(_14_),
    .Y(_11_)
  );
  NOR _42_ (
    .A(_18_),
    .B(_12_),
    .Y(_13_)
  );
  NOR _43_ (
    .A(_29_),
    .B(_28_),
    .Y(_24_)
  );
  NOR _44_ (
    .A(_24_),
    .B(_26_),
    .Y(_15_)
  );
  always @(posedge clk or posedge rst)
    if (rst)
      ps[0] <= 1;
    else
      ps[0] <= _01_;
  always @(posedge clk or posedge rst)
    if (rst)
      ps[1] <= 0;
    else
      ps[1] <= _03_;
  always @(posedge clk or posedge rst)
    if (rst)
      ps[2] <= 0;
    else
      ps[2] <= _05_;
  always @(posedge clk or posedge rst)
    if (rst)
      ps[3] <= 0;
    else
      ps[3] <= _00_;
  always @(posedge clk or posedge rst)
    if (rst)
      ps[4] <= 0;
    else
      ps[4] <= _06_;
  assign w = ps[1];
  assign _09_ = ps[0];
  assign _21_ = ps[3];
  assign _25_ = ps[4];
  assign _26_ = j;
  assign _00_ = _27_;
  assign _28_ = ps[1];
  assign _29_ = ps[2];
  assign _01_ = _10_;
  assign _03_ = _11_;
  assign _05_ = _13_;
  assign _06_ = _15_;
endmodule
